name: Price Scraper

on:
  schedule:
    - cron: '0 */8 * * *'  # Cada 8 horas
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        cache: 'pip'

    - name: Install dependencies
      run: pip install -r backend/requirements.txt

    - name: Run scraper
      run: python backend/scraper.py

    - name: Commit results
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add backend/data/precios.json
        git commit -m "Update precios $(date -u +"%Y-%m-%dT%H:%M:%SZ")" || echo "No hay cambios"
        git push
